name: Statistics-Regression
version: 0.15
abstract: weighted linear regression package (line+plane fitting)
author: Ivo Welch <ivo.welch@yale.edu>
license: GPL
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
